sonar.projectKey=certificate-generator
sonar.projectName=Certificate Generator

sonar.sources=app,components,lib,hooks
sonar.tests=__tests__,lib/__tests__,e2e,tests
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.test.tsx,**/.next/**,**/__tests__/**,**/playwright-report/**,**/test-results/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8