sonar.projectKey=TheScientis_certificate-generator-v2
sonar.organization=thescientis

sonar.sources=app,components,lib,hooks
sonar.tests=__tests__,lib/__tests__,e2e,tests
sonar.exclusions=node_modules/**,.next/**,playwright-report/**,test-results/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8